name: Daily Check-in

on:
  schedule:
    #- cron: '0 1 * * *'  # 每天1点 UTC 时间执行
    - cron: "44 17,7 * * *"

  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@main
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 2
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.19'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LINUXDO_USERNAME: ${{ secrets.LINUXDO_USERNAME }}
          LINUXDO_PASSWORD: ${{ secrets.LINUXDO_PASSWORD }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BROWSE_ENABLED: ${{ secrets.BROWSE_ENABLED }}
        run: |
          python main.py

      - name: Random Cron
        uses: grbnb/random-workflow-cron@dev
        with:
          github_token: ${{ secrets.PAT }}
          #push_switch: false
          keep_history: true
          time_zone: "UTC+8"
          hour_start: 0
          hour_end: 21
          interval_count: 2
